version: '3.6'

services:
  db:
    image: mysql:5.7
    container_name: db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      command: --default-authentication-plugin=mysql_native_password
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      